spring:
  application:
    name: shorter
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true